### ISSUE TITLE
Add support for UIBarButtonItems

### ISSUE THREAD

**Issue by kacperd** [michalciurus/Outletgen#11]

**Comment by kacperd** [comment]
@michalciurus UIBarItems also have no restorationID. It would be nice to have the same interface for setting ids on views which are later used to generate outlets. 

How about using extensions to add some kind of @IBInspectable outletgenIdentifier field to all classes that can be then discovered by outletgen. In extensions we can actually hide implementation details and use restorationIDs, identifiers etc.

```
extension UIBarItem {
    @IBInspectable var outletgenIdentifier: String {
        set {
            
        }
        get {
            
        }
    }
}
```

**Comment by michalciurus** [comment]
Yep, sounds good @kacperd !!
