### ISSUE TITLE
Add support for constraint outlets

### ISSUE THREAD

**Issue by michalciurus** [michalciurus/Outletgen#4]

**Comment by kacperd** [comment]
I can do this, but some clarification first. 
There is no restoration identifier for constraints so  what will be better:
- Use constraint Identifier 
- Use userDefinedRuntimeAttributes and set restorationID there
- Something else?

**Comment by michalciurus** [comment]
@kacperd constraint id seems like the way to go?

**Comment by kacperd** [comment]
Ok, so lets do it with constraint id.
